# Generated by Django 3.2.3 on 2021-05-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('is_alum', models.BooleanField(default=True)),
                ('in_office', models.BooleanField(default=False)),
                ('pass_year', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
